sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cele3x/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cele3x/react-test npm test

after_success:
  - docker build -t cele3x/multi-client ./client
  - docker build -t cele3x/multi-nginx ./nginx
  - docker build -t cele3x/multi-server ./server
  - docker build -t cele3x/multi-worker ./worker
  # Log in to the docker CLI (using env variables)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push cele3x/multi-client
  - docker push cele3x/multi-nginx
  - docker push cele3x/multi-server
  - docker push cele3x/multi-worker